import {Inter,Calistoga} from "next/font/google"
import "./globals.css";

const inter = Inter({subsets:["latin"],variable:"--font-sans"});


const calistoga = Calistoga({subsets:["latin"],variables:"--font-serif",weight:["400"]});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-900 text-white scroll-smooth
            ${inter.variable} ${calistoga.variable} font-sans antialiased `}
      >
        
        {children}
      </body>
      {/* bg-[#205781] */}
    </html>
  );
}
